# This code was generated by a tool.
# @basketry/sorbet@{{version}}
# 
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Enums
  class ExhaustiveParamsPathEnumArray < T::Enum
    enums do
      ONE = new('one')
      TWO = new('two')
      THREE = new('three')
    end
  end
end
