# This code was generated by a tool.
# @basketry/sorbet@{{version}}
# 
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Enums
  class ProductSize < T::Enum
    enums do
      SMALL = new('small')
      MEDIUM = new('medium')
      LARGE = new('large')
    end
  end
end
