# This code was generated by a tool.
# @basketry/sorbet@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Types
  class ExhaustiveParamsBody < T::Struct
    const :foo, T.nilable(String)
    const :bar, T.nilable(String)
  end
end
