# This code was generated by @basketry/sorbet@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
# 
# To make changes to the contents of this file:
# 1. Edit source/path.ext
# 2. Run the Basketry CLI
#
# About Basketry: https://github.com/basketry/basketry#readme
# About @basketry/sorbet: https://github.com/basketry/sorbet#readme

# typed: strict

module BasketryExample::V1::Types
  class GizmosResponse < T::Struct
    const :data, T::Array[BasketryExample::V1::Types::Gizmo]
  end
end
