# This code was generated by a tool.
# @basketry/sorbet@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Types
  class NewWidgetFoo < T::Struct
    const :fiz, T.nilable(Numeric)
    const :buzz, Numeric
  end
end
