# This code was generated by a tool.
# @basketry/sorbet@{{version}}
# 
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Types
  # Type for creating a new Widget Foo
  class NewWidgetFoo < T::Struct
    # The fizziest fiz
    const :fiz, T.nilable(Numeric)

    # The buzziest buzz
    const :buzz, Numeric
  end
end
