# This code was generated by a tool.
# @basketry/sorbet@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Types
  class Widget < T::Struct
    const :id, String
    const :name, T.nilable(String)
    const :fiz, Numeric
    const :buzz, T.nilable(Numeric)
    const :fizbuzz, T.nilable(Numeric)
    const :foo, T.nilable(BasketryExample::V1::Types::WidgetFoo)
    const :size, T.nilable(BasketryExample::V1::Enums::ProductSize)
  end
end
