# This code was generated by a tool.
# @basketry/sorbet@{{version}}
# 
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1
  module AuthPermutationService
    extend T::Sig
    extend T::Helpers

    interface!

    sig { abstract.void }
    def all_auth_schemes
    end

    sig { abstract.void }
    def combo_auth_schemes
    end
  end
end
