# This code was generated by a tool.
# @basketry/sorbet@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1
  module GizmoService
    extend T::Sig
    extend T::Helpers

    interface!

    # Only has a summary
    sig do
      abstract.params(
        search: T.nilable(String)
      ).returns(
        T.nilable(BasketryExample::V1::Types::GizmosResponse)
      )
    end
    def get_gizmos(search:)
    end

    # Has a summary in addition to a description
    # Has a description in addition to a summary
    sig do
      abstract.params(
        size: T.nilable(BasketryExample::V1::Enums::CreateGizmoSize)
      ).returns(
        T.nilable(BasketryExample::V1::Types::Gizmo)
      )
    end
    def create_gizmo(size:)
    end

    sig do
      abstract.params(
        factors: T.nilable(T::Array[String])
      ).returns(
        T.nilable(BasketryExample::V1::Types::Gizmo)
      )
    end
    def update_gizmo(factors:)
    end
  end
end
