export const warning = `# This code was generated by a tool.
# ${require('../package.json').name}@${require('../package.json').version}
# 
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.`;
