import { Service } from 'basketry';

export const warning = (
  service: Service,
  pkg: {
    name: string;
    version: string;
    homepage?: string;
  },
) => `# This code was generated by ${pkg.name}@${pkg.version}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
# 
# To make changes to the contents of this file:
# 1. Edit ${service.sourcePath}
# 2. Run the Basketry CLI
#
# About Basketry: ${require('basketry/package.json').homepage}${
  pkg.homepage ? `\n# About ${pkg.name}: ${pkg.homepage}` : ''
}`;
